dataset:
  input_size: 224
  batch_size: 16
  limit_train_per_class: 0
  limit_val_per_class: 0

model:
  num_classes: 9
  pretrained_weights: "./pretrain_weights/convnext_tiny_1k_224_ema.pth"

train:
  epochs_stage1: 20
  epochs_stage2: 30
  grad_clip: 0.5

criterion:
  label_smoothing: 0.05

optimizer:
  lr_stage1: 0.001
  lr_stage2: 0.00005
  beta1: 0.9
  beta2: 0.999
  eps: 1e-8
  weight_decay1: 0.02
  weight_decay2: 0.02

early_stop:
  patience: 7
  min_delta: 0.002

scheduler:
  reduce:
    mode: "max"
    factor: 0.5
    patience: 2
    min_lr: 5e-7
  cosin:
    warmup_epochs: 4
    warmup_lr_init: 1e-7
    min_lr: 5e-8
  warmup_epochs_stage1: 4
  warmup_lr_init_stage1: 1e-7

logger:
  model_name: "convnext_tiny_complex"
