dataset:
  input_size: 224
  batch_size: 24
  limit_train_per_class: 0
  limit_val_per_class: 0

model:
  num_classes: 185
  pretrained_weights: "./pretrain_weights/convnext_tiny_1k_224_ema.pth"
  dropout: 0.15

optimizer:
  lr_stage1: 3.5e-4
  lr_stage2: 2.5e-5
  beta1: 0.9
  beta2: 0.999
  eps: 1e-8
  weight_decay1: 5e-5
  weight_decay2: 0.08

criterion:
  label_smoothing: 0.18

train:
  epochs_stage1: 10
  epochs_stage2: 20
  grad_clip: 0.8

early_stop:
  patience: 4
  min_delta: 0.002

logger:
  model_name: "convnext_tiny_single_stable"

scheduler:
  reduce:
    mode: "max"
    factor: 0.5
    patience: 1
    min_lr: 5e-7
  cosin:
    warmup_epochs: 3
    warmup_lr_init: 1e-5
    min_lr: 5e-7
  warmup_epochs_stage1: 0
