dataset:
  input_size: 224
  batch_size: 32
  limit_train_per_class: 0
  limit_val_per_class: 0

model:
  num_classes: 185

train:
  epochs_stage1: 10
  epochs_stage2: 25
  grad_clip: 1.0

optimizer:
  lr_stage1: 0.001
  lr_stage2: 0.0001
  beta1: 0.9
  beta2: 0.999
  eps: 1e-8
  weight_decay: 0.004

early_stop:
  patience: 3
  min_delta: 0.001

scheduler:
  mode: "max"
  factor: 0.5
  patience: 1
  min_lr: 1e-6
